Champion.destroy_all
Skill.destroy_all

fizz = Champion.create(name: "Fizz", img_url: "http://vignette2.wikia.nocookie.net/leagueoflegends/images/f/f8/Fizz_OriginalLoading.jpg/revision/latest/scale-to-width-down/110?cb=20160525001421")
talon = Champion.create(name: "Talon", img_url: "http://vignette1.wikia.nocookie.net/leagueoflegends/images/b/bd/Talon_OriginalLoading.jpg/revision/latest/scale-to-width-down/110?cb=20160526042803")
annie = Champion.create(name: "Annie", img_url: "http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/Annie.png")

Skill.create(name: "Urchin Strike", img_url:"http://vignette4.wikia.nocookie.net/leagueoflegends/images/a/a4/Urchin_Strike.png/revision/latest?cb=20161018213436", video_url: "https://www.youtube.com/watch?v=K0n5djxsbKM", description: "Fizz dashes through his target, dealing 100% Attack Damage physical damage plus 10/25/40/55/70 (+35% Ability Power) magic damage. This spell applies on-hit effects. Seastone Trident is applied to all enemy units Fizz passes through during his dash.", champion: fizz )
Skill.create(name: "Seastone Trident", img_url:"http://vignette1.wikia.nocookie.net/leagueoflegends/images/6/6d/Seastone_Trident.png/revision/latest?cb=20161018213411", video_url: "https://www.youtube.com/watch?v=5HJHmYUo1RE", description: "Fizz's attacks bleed his enemies, dealing magic damage over several seconds. Fizz can empower his next attack to deal bonus damage, increased by how long the bleed was active on his target.", champion: fizz)
Skill.create(name: "Noxian Diplomacy", img_url: "http://vignette1.wikia.nocookie.net/leagueoflegends/images/6/6b/Noxian_Diplomacy.png/revision/latest/scale-to-width-down/64?cb=20161030003733", video_url:"https://www.youtube.com/watch?v=D2ontx46CXc", description: "Talon stabs the target unit. If they are within melee range, this attack deals critical damage.", champion: talon)
Skill.create(name: "Rake", img_url: "http://vignette3.wikia.nocookie.net/leagueoflegends/images/b/bd/Rake.png/revision/latest/scale-to-width-down/64?cb=20161030003735", video_url: "https://www.youtube.com/watch?v=K6m89ZY6lI0", description: "Talon sends out a volley of daggers that then return back to him, dealing physical damage every time it passes through an enemy.", champion: talon)
Skill.create(name: "Disintegrate", img_url: "http://vignette2.wikia.nocookie.net/leagueoflegends/images/2/25/Disintegrate.png/revision/latest?cb=20130929122652", video_url: "https://www.youtube.com/watch?v=h46Waxe1HEc", description: "Annie hurls a Mana infused fireball, dealing damage and refunding the Mana cost if it destroys the target.", champion: annie)
